site_name: HJ-Prox Code
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: google
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/howardheaton
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TypalResearch
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@TypalResearch
