[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "A Hamilton-Jacobi-based Proximal Operator"
authors = [{name = "Samy Wu Fung, Howard Heaton", email = "swufung@mines.edu"}]
dynamic = ["version", "description"]
